title: Musician's Toolbox
description: The all-in-one tool for musicians

theme: minima
minima:
  skin: auto
  # TODO: Fix social links, and add Google Play and App Store
  social_links:
    - { platform: github,  user_url: "https://github.com/BeMain" }

header_pages:
  - PRIVACY_POLICY.md

author: Benjamin Agardh
email: bemain.dev@gmail.com

