// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoAS8gqhWcerv47jFwO5n1-C4gHCMc0iM',
    appId: '1:218081465637:web:7405cfa79f01edfc45b6cc',
    messagingSenderId: '218081465637',
    projectId: 'musicians-toolbox',
    authDomain: 'musicians-toolbox.firebaseapp.com',
    storageBucket: 'musicians-toolbox.firebasestorage.app',
    measurementId: 'G-FRNERYWZGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgTmhrOWN0dRTg7Mp5SM6EMhcH8OuBz0s',
    appId: '1:218081465637:android:a5e3d56b594ae8df45b6cc',
    messagingSenderId: '218081465637',
    projectId: 'musicians-toolbox',
    storageBucket: 'musicians-toolbox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGGGwgxElk5C6bVRIHaKcr9HCDbqmA6BI',
    appId: '1:218081465637:ios:bc54885b544f9ef045b6cc',
    messagingSenderId: '218081465637',
    projectId: 'musicians-toolbox',
    storageBucket: 'musicians-toolbox.firebasestorage.app',
    iosBundleId: 'se.agardh.musbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGGGwgxElk5C6bVRIHaKcr9HCDbqmA6BI',
    appId: '1:218081465637:ios:27374b6f5ff79a8945b6cc',
    messagingSenderId: '218081465637',
    projectId: 'musicians-toolbox',
    storageBucket: 'musicians-toolbox.firebasestorage.app',
    iosBundleId: 'se.agardh.musbx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoAS8gqhWcerv47jFwO5n1-C4gHCMc0iM',
    appId: '1:218081465637:web:298208a6ef59578d45b6cc',
    messagingSenderId: '218081465637',
    projectId: 'musicians-toolbox',
    authDomain: 'musicians-toolbox.firebaseapp.com',
    storageBucket: 'musicians-toolbox.firebasestorage.app',
    measurementId: 'G-6RZWT39P4Z',
  );
}
