default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)
  
    sh "flutter build ipa --release"

    build_app(
      scheme: "Runner",
      export_method: "app-store",
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )
    
    upload_to_testflight
  end
end