default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)
  
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "se.agardh.musbox" => "Distribute to App Store" 
        }
      },
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )
    
    upload_to_testflight
  end
end