default_platform(:android)

platform :android do
  desc "Build and upload to Google Play Beta Track"
  lane :beta do
    sh "flutter build appbundle --release"

    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end