default_platform(:android)

platform :android do
  desc "Build and upload to Google Play Beta Track"
  lane :beta do
    gradle(task: 'assemble', build_type: 'Release')

    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      # json_key_data: ENV['ANDROID_SERVICE_ACCOUNT_JSON'], # Injected from Secret
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end