name: Flutter Build & Deploy

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'both'
        type: choice
        options:
          - android
          - ios
          - both
      bump_build: 
        description: 'Increase build number'
        required: false
        type: boolean
        default: true

  release:
    types: [published]

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.platforms.outputs.platforms }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Determine platforms
        id: platforms
        run: |
          if [[ "${{ github.event_name }}" == "release" || "${{ github.event.inputs.platform }}" == "both" ]]; then
            echo 'platforms=["android", "ios"]' >> $GITHUB_OUTPUT
          else
            echo 'platforms=["${{ github.event.inputs.platform }}"]' >> $GITHUB_OUTPUT
          fi

      - name: Calculate Version and Build Number
        id: vars
        run: |
          VERSION=$(grep "^version:" pubspec.yaml | cut -d' ' -f2)

          # Determine build number
          BUILD=$(echo "$VERSION" | cut -d'+' -f2)
          if [[ "${{ github.event_name }}" != "release"  && "${{ github.event.inputs.bump_build }}" == "true" ]]; then
            BUILD=$((BUILD + 1))
          fi
          echo "build_number=$BUILD" >> $GITHUB_OUTPUT
          
          # Determine version name
          if [[ "${{ github.event_name }}" == "release" ]]; then
            # Strip 'v' from tag (e.g., v1.2.3 -> 1.2.3)
            VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          else
            # Get current version from pubspec
            VERSION=$(echo "$VERSION" | cut -d'+' -f1)
          fi
          echo "version_name=$VERSION" >> $GITHUB_OUTPUT

      - name: Update Pubspec and Commit
        run: |
          VERSION="${{ steps.vars.outputs.version_name }}"
          BUILD="${{ steps.vars.outputs.build_number }}"
          sed -i "s/^version: .*/version: $VERSION+$BUILD/" pubspec.yaml
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pubspec.yaml
          if git diff-index --quiet HEAD --; then
              echo "No changes to commit."
          else
              git commit -m "chore: build version $VERSION+$BUILD [skip ci]"
          fi
          git push

      - name: Generate Changelog
        if: github.event_name == 'release'
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release Description
        if: github.event_name == 'release'
        run: |
          gh release edit ${{ github.event.release.tag_name }} --notes "${{ steps.changelog.outputs.changelog }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.prepare.outputs.platforms) }}

    runs-on: ${{ (matrix.platform == 'ios') && 'macos-latest' || 'ubuntu-latest' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          ref: main
    
      - name: Fetch material_plus dependency
        run: git clone --depth=1 https://gitlab.com/flutterby-group/material_plus.git ../material_plus
      
      - name: Write keys.dart to file
        run: |
          cat << EOF > ./lib/keys.dart
          ${{ secrets.KEYS_FILE }}
          EOF
      
      - name: Decode Android files
        if: matrix.platform == 'android'
        run: |
          echo "${{ secrets.ANDROID_UPLOAD_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" > android/key.properties
          echo "${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON_BASE64 }}" | base64 --decode > ../musbx-service-account-key.json

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      
      - name: Install Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Run Fastlane
        working-directory: ${{matrix.platform}}
        env:
          CI: true # Tell Fastlane we are in a CI

          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }} # Password for fastlane (iOS only)
          FASTLANE_DONT_STORE_PASSWORD: 1

          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_UPLOAD_KEYSTORE_PASSWORD }} # Password for keystore (Android only)

          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # Password for fastlane match (iOS only)
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION_BASE64 }} # Git authorization for fastlane match (iOS only)
        run: |
          bundle install
          bundle exec fastlane beta

      - name: Upload Artifacts to Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ matrix.platform }}" == "android" ]; then
            gh release upload ${{ github.event.release.tag_name }} build/app/outputs/bundle/release/app-release.aab
          else
            gh release upload ${{ github.event.release.tag_name }} ios/build/Runner.ipa
          fi
